apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: postgres-scc
  namespace: postgresql
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowedCapabilities: []
allowPrivilegeEscalation: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:postgresql:default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgresql
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        runAsUser: 999 # OpenShift's restricted SCC requires non-root users
        runAsGroup: 999
        fsGroup: 999
      containers:
      - name: postgres
        image: public.ecr.aws/r2u9e8v0/postgresql:latest
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "P@ssword"
        - name: POSTGRES_DB
          value: "db-admin"
        - name: postgres-storage
          value: "/var/lib/postgresql/data/pgdata"
        securityContext:
          runAsUser: 999 # OpenShift's restricted SCC requires non-root users
          runAsGroup: 999
          fsGroup: 999
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgre-single
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgresql
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: postgres
  namespace: postgresql
spec:
  to:
    kind: Service
    name: postgres
  port:
    targetPort: 5432
