namePrefix: staging-
namespace: postgresql

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: secret.yaml
- path: nodeport.yaml
- path: deployment.yaml
