apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432           # The port that the container listens on
    targetPort: 5432     # The port to target within the pod
    nodePort: 32000      # The port exposed on the node (must be in the range 30000-32767)