#apiVersion: security.openshift.io/v1
#kind: SecurityContextConstraints
#metadata:
#  name: postgres-scc
#  namespace: default
#allowHostDirVolumePlugin: false
#allowHostIPC: false
#allowHostNetwork: false
#allowHostPID: false
#allowHostPorts: false
#allowPrivilegedContainer: false
#allowedCapabilities: []
#allowPrivilegeEscalation: false
#runAsUser:
#  type: RunAsAny
#seLinuxContext:
#  type: MustRunAs
#fsGroup:
#  type: RunAsAny
#supplementalGroups:
#  type: RunAsAny
#users:
#- system:serviceaccount:postgresql:default
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      #securityContext:
        #runAsUser: 999 # OpenShift's restricted SCC requires non-root users
        #runAsGroup: 999
        #fsGroup: 999
      containers:
      - name: postgres
        image: quay.klgsys.com/mirror/postgres
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "4"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_DB
          value: "db-admin"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: postgres-storage
          value: "/var/lib/postgresql/data/pgdata"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgre-single-dev
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432           # The port that the container listens on
    targetPort: 5432     # The port to target within the pod
    nodePort: 31000      # The port exposed on the node (must be in the range 30000-32767)